language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update

script: bin/idx buildTravis

after_script:
  - bin/test-reporter --coverage-report=clover.xml

after_success:
  - mkdir -p ~/.ssh
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_6ab1bc8a1906_key -iv $encrypted_6ab1bc8a1906_iv -in id_rsa_idephix_doc.enc -out ~/.ssh/id_rsa -d'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bin/idephix.phar deployPhar'

addons:
  code_climate:
    repo_token: d78a2bee0da040438a789f86c200b705caaa43eea2358a2610cef18e3960f145

notifications:
  slack:
    secure: URHeOIN40h7mayLQTVhjyT16y9ritiZQgYe1zz25xM7pLD0T3YiIeYB9QTx6SqOUwsya7Jv+jDUQXEtiIzZoXLkZS2ZoCJPAzPTI8NY/DgeGnMzt/NxAuM2t0K9l+ECWf3Bt8XFud881uZKj5Ir+uzAoI5mkyNrjQrw91l2U0ju/oY+DY4JtuS9NoSn3/WntczsKEP9r2xKvLojgKVpkhdsoFbb4cAWAwICLBhGq2AQMuakalV3tH80SaS0G02Zkfwo6eXQ5kkCrO6cjFHWeCcfETCW+WvcCQzatuKQg06KRCyt7DJUUp7qmDyqm0A34catPAh6jm3HdayE5g6WbTGcArGieEYJ9xd42Oc/C32u/Le58Qpe17sLD0tD6Hn79SP2s3vTTjpVdoML0Upgy3ZT1sTQzTBvUoObrDR/fxZnlewnRfcfRwSin8oLzLIvVIVB4frByBZidqcTpavR1EyJsUe1BgB68cef2l0FksTOugoVevU/55VLyP8rNlU6Hylk7ZNLBXOiGOnv7wkUnl6vKTIGpCSNgzh8aIGEXrCfpjdgHQOGcd5tktg4D16m1W3k26RXHssAImJ+BJuNu4hB3ouj21gh5k2sAz/jIQ7TfJBsFeo7+vEvym4FpPyqD/MM3dA2s5vYcWwe400MQfSdyK3p4ATYR2r8I8XlTlmE=
